### ISSUE TITLE
Sparks can't be shared between servers

### ISSUE THREAD

**Issue by jedmund** [jedmund/siero-bot#44]
We are able to store multiple guild IDs in the spark database, but we never do. Therefore, a user's spark will only show up in the leaderboard of the first server they interact with Siero in.

**Comment by FlawedBliss** [comment]
Why not drop guild ids entirely and generate the leaderboard based on the guilds member list? That way a users spark will show up on every server they're a member of and there's no need to keep track of a users guilds anymore. Currently, users would still show up after leaving a guild too.

**Comment by jedmund** [comment]
@FlawedBliss I'm only just seeing this but this is a very good idea! Thank you. If you or someone else wants to take this up, feel free. Otherwise, I'll get to it when I get to it.

**Comment by jedmund** [comment]
@FlawedBliss fixed this in #82 . We should continue doing the same for `$profile` soon so we can stop storing guild ids.
